// <copyright file="MainForm.Designer.cs" company="PublicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace BookSynopsisTemplate
{
    partial class ViewHtmlForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
        	this.htmlTextBox = new System.Windows.Forms.TextBox();
        	this.SuspendLayout();
        	// 
        	// htmlTextBox
        	// 
        	this.htmlTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.htmlTextBox.Location = new System.Drawing.Point(0, 0);
        	this.htmlTextBox.Multiline = true;
        	this.htmlTextBox.Name = "htmlTextBox";
        	this.htmlTextBox.Size = new System.Drawing.Size(284, 262);
        	this.htmlTextBox.TabIndex = 0;
        	// 
        	// ViewHtmlForm
        	// 
        	this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        	this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        	this.ClientSize = new System.Drawing.Size(284, 262);
        	this.Controls.Add(this.htmlTextBox);
        	this.Name = "ViewHtmlForm";
        	this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        	this.Text = "Current HTML";
        	this.ResumeLayout(false);
        	this.PerformLayout();
        }
        private System.Windows.Forms.TextBox htmlTextBox;
    }
}
